name: AWS Command on Push

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  aws-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install python3 python3-pip -y
          pip3 install awscli
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::8450209857:role/preevy-github-action
          aws-region: us-east-1
          role-session-name: my-session-name
      
      - name: Run AWS Command
        run: |
          aws sts get-caller-identity
